cluster_name            = "DevOps"
key_pair                = "fayis-key"
instance_types          = ["t3.large"]
instance_type_BH        = "t3.micro"
node_group_name         = "eks-cluster-123-node-group"
public_access_cidrs     = ["0.0.0.0/0"]
tags                    = "DevOps-vpc"
tags2                   = "DevOps-vpc2"
vpc_cidr                = "10.0.0.0/16"
instance_tenancy        = "default"
public_sn_count         = "2"
private_sn_count        = "2"
public_cidrs            = ["10.0.1.0/24", "10.0.2.0/24"]
private_cidrs           = ["10.0.3.0/24", "10.0.4.0/24"]
rt_route_cidr_block     = "0.0.0.0/0"
access_ip               = "0.0.0.0/0"
scaling_desired_size    = "2"
scaling_max_size        = "2"
scaling_min_size        = "1"
map_public_ip_on_launch = "true"
key_name                = "fayis-key"
ami_id                  = "ami-020cba7c55df1f615"
aws_region = "us-east-1"